### PR TITLE
Fix source name

### PR DESCRIPTION
**Pull request by tyfkda**

### CODE REVIEW

**Comment by hollasch** [comment]
Looks good. Please target dev-patch.

**Comment by tyfkda** [comment]
@hollasch Thank you for your review!
I've changed target branch to dev-path.

**Comment by hollasch** [comment]
@tyfkda — can you let me know your real name, so I can add you to the book credits? Thanks.

**Comment by tyfkda** [comment]
@hollasch Thank you for your kindness, but my change was very small so I don't think my name should be added to the credit.

**Comment by hollasch** [comment]
Well, ok, but that means you need to add a bigger change then. `:D`

**Pull request merged**
