### PR TITLE
Use shared_ptr for materials and objects

### PR DESCRIPTION
**Pull request by hollasch**
For src/inOneWeekend code only.

### CODE REVIEW

**Comment by hollasch** [comment]
Up for consideration. Do we want to do this? It eliminates the memory leaks, particularly in multi-frame scenarios. The cost is additional C++ jargon. We'll have to go over this in the books, but it shouldn't be too hard.

**Comment by trevordblack** [comment]
I give a tentative approval to the addition of `shared_ptr`

**Comment by petershirley** [comment]
I think it's a good idea.

**Comment by hollasch** [comment]
Superseded by #328

**Pull request closed without merging**
