### PR TITLE
Fix jitter sample bug

### PR DESCRIPTION
**Pull request by hollasch**
Fixes a bug I introduced with the camera rewrite, where I thought I was optimizing things.

### CODE REVIEW

**Comment by trevordblack** [comment]
I might not be able to get around to this until the weekend. Is that alright?

**Comment by hollasch** [comment]
No rush.

**Comment by trevordblack** [comment]
I'm not sure what you're fixing here, `auto t` is inside of the outer for loop on lines 1624, 1804, 2850, etc.

I'm approving this commit to unblock you

**Review by trevordblack — APPROVED** [review]

**Comment by hollasch** [comment]
The bug here is that we're generating `samples_per_pixel` random s,t coordinates, but the result of my earlier "optimization" (moving the t-calculation outside the innermost loop) is that all samples will be along a constant t line, instead of within in the sampling box.

**Comment by hollasch** [comment]
This showed up as odd/significant aliasing for horizontally-oriented edges.

**Comment by hollasch** [comment]
This fixed #1065.

**Pull request merged**
