### PR TITLE
Fix diffuse (should use random point on unit sphere, not inside it)

### PR DESCRIPTION
**Pull request by aras-p**
Should fix issue #145, see also https://aras-p.info/blog/2018/03/31/Daily-Pathtracer-Part-4-Fixes-Mitsuba/

### CODE REVIEW

**Comment by hollasch** [comment]
@aras-p — see my comments in PR #182 (https://github.com/RayTracing/raytracing.github.io/pull/182). Let me know if you want to rework this; if not, I'll tackle it.

**Comment by aras-p** [comment]
I can rework this in a few days.

**Comment by aras-p** [comment]
@hollasch merged latest master branch; should be no conflicts now.

**Comment by trevordblack** [comment]
Should be merged with `development` branch. I believe

**Comment by aras-p** [comment]
> Should be merged with `development` branch. I believe

I can, but the contributing guide doc does not mention it. Should I merge it?

**Comment by hollasch** [comment]
I'm breaking these up to focused commits (one issue at a time), targeting the development branch. Please review https://github.com/RayTracing/raytracing.github.io/pull/229, even though it will be closed by the time you see this, I should see commentary if there are any issues.

I've also extended an invite (to @aras-p) to make collaboration easier. Send me (steve@hollasch.net) your email address and I can send you an invitation to our workspace on Slack if you're interested.

**Comment by hollasch** [comment]
Implemented in PR #229, development branch.

**Pull request closed without merging**
