### PR TITLE
Fix hittable filename typo

### PR DESCRIPTION
**Pull request by bennetthardwick**
`InOneWeekend` fails to compile, complaining:
```
hittable_list.h: No such file or directory
```

Looks like there was some left over typos from #184.

Thanks!

### CODE REVIEW

**Comment by trevordblack** [comment]
Add it to the changelog

**Comment by bennetthardwick** [comment]
@trevordblack I've updated the change log to include this PR and #184. Perhaps you could update contributing guidelines so new contributors know to update this file with their changes?

**Comment by trevordblack** [comment]
The "update the CHANGELOG" was a comment for @ronaldfw

This is an opinion we might change in the future, but at present, we don't
want users to update the guides (CHANGELOG, readmes)

**Comment by bennetthardwick** [comment]
Ah okay no worries, I've reverted my changes.

**Comment by ronaldfw** [comment]
@trevordblack Thanks for the reminder, will update the changelog once this is merged.

**Pull request merged**
