### PR TITLE
ref: change order check

### PR DESCRIPTION
**Pull request by sshaplygin**
Little bit refactoring. We don't need create `hit_record rec;` objects if `depth <= 0` condition is true.

### CODE REVIEW

**Comment by hollasch** [comment]
This should not go into the active release.

**Comment by sshaplygin** [comment]
Hey, @hollasch Thanks for your answer. 
> This should not go into the active release.

What's need to do that change go to the active release?

**Comment by hollasch** [comment]
The developers package patch, minor or major revisions for official packaged releases to the community. Did you read CONTRIBUTING.md?

**Comment by hollasch** [comment]
Looks like just switching this from targeting our `release` branch to the proper `dev` branch slipped in some release branch changes. Seems like these changes should just be rebased (or cherry-picked) for the `dev` branch.

**Comment by hollasch** [comment]
Rebased to `dev` branch with small additional changes: PR #1320.

**Pull request closed without merging**
