### PR TITLE
Sketch of possible citation section for book 1

### PR DESCRIPTION
**Pull request by hollasch**
**Proposal**, please comment. See associated issue #500.

Ping: @yordrar

### CODE REVIEW

**Comment by trevordblack** [comment]
Looks good to me

**Comment by petershirley** [comment]
Looks good to me too

**Comment by petershirley** [comment]
Oops I closed it and meant

**Comment by hollasch** [comment]
Oops; that was just a proposal/sketch PR. I had made-up dates for release and the other two books have nothing. 😄

**Pull request merged**
