### PR TITLE
Header sort

### PR DESCRIPTION
**Pull request by hollasch**
Lots of header simplification and reorganization.

### CODE REVIEW

**Comment by trevordblack** [comment]
1. Move `ffmax` and `ffmin` somewhere else
2. Maybe move all `random_.*` into their own random.h header
3. Move surface_texture.h inside texture.h
4. Maybe collect all material.h into common

What's the cut-off for what makes it into common and what doesn't?
That should probably codified somewhere.

**Comment by trevordblack** [comment]
As much as possible, I don't want this collation to infect the text.

**Comment by hollasch** [comment]
Created https://github.com/RayTracing/raytracing.github.io/issues/294 for the random functions.

**Comment by hollasch** [comment]
Created #295 for the `surface_texture.h` → `texture.h` move.

**Comment by hollasch** [comment]
I looked at `material.h`, but that one's a hairball.

**Comment by hollasch** [comment]
Holding on this PR to merge in pending PR #279 .

**Pull request merged**
