### PR TITLE
Fix typo: "consine" to "cosine"

### PR DESCRIPTION
**Pull request by shaunplee**

### CODE REVIEW

**Comment by hollasch** [comment]
Thank you!

**Comment by hollasch** [comment]
I'm planning on releasing the patch branch next weekend.

**Comment by shaunplee** [comment]
Thanks! I've been enjoying the book very much and had just implemented "Defocus Blur" when 3.0.0 came out, which has given me an excuse to reread it from the beginning and rewrite my code to track.

**Comment by hollasch** [comment]
Excellent. We've been getting a bunch of issues reported from another reader who's working through book two, so would really appreciate any feedback.

Oh, we'll also add you to the credits. How would you like your name spelled? Is it Shawn P. Lee?

**Comment by shaunplee** [comment]
Understood. I'll review a little more and maybe submit issues on other topics (likely at least something relating to how defocus blur works).

Oh, that's nice. "Shaun P. Lee" would be fine. Thanks!

**Pull request merged**
