### PR TITLE
Update static Markdeep from 1.13 to 1.15

### PR DESCRIPTION
**Pull request by hollasch**
Normally, our books automatically use the latest version of Markdeep, but we also include a static version for those who are offline. This change updates the static version to the latest.

See https://casual-effects.com/markdeep/#history for changes.

### CODE REVIEW

**Comment by trevordblack** [comment]
I'm not seeing any visual artifacts, but I am seeing differences in the way that code gets colored

**Comment by trevordblack** [comment]
Screenshot from 2023-07-13 16-36-50
Screenshot from 2023-07-13 16-36-58
Screenshot from 2023-07-13 16-37-11
Screenshot from 2023-07-13 16-37-18

**Comment by trevordblack** [comment]
I don't think the change is necessarily bad, which do you think is better?

**Comment by hollasch** [comment]
Code style will be reviewed and addressed in #868.

**Review by trevordblack — APPROVED** [review]
If code coloring cannot be changed I may request this gets reverted

**Comment by hollasch** [comment]
Pinning ourselves to an old version for code styling would be a bad decision in my opinion. Either way, we can address in CSS.

**Pull request merged**
