### PR TITLE
Override keyword added to all books and code

### PR DESCRIPTION
**Pull request by D-K-E**
"override" qualifier is added to all derived classes.
The qualifier is also added to the text of all the  books. I might have missed one or two but normally it should be there. 
A quick note: The `scatter` method of `isotropic` class does not override that of base class but it overloads it in the last book, so I have not touched upon it. 
I also don't have markdeep formatting library, so it is very much possible that the text of the book looks poorly formatted.

All the code compiles and no runtime error
during the execution.
I have only tested the three main executables:
inOneWeekend
theNextWeek
theRestOfYourLife

Related to #639

### CODE REVIEW

**Comment by trevordblack** [comment]
what's with all of the changes to the source code at the end of the diff? Was that your changes, or did you forget to `git pull`.

There's a lot in here that's not just `override`

**Comment by trevordblack** [comment]
what's with all of the changes to the source code at the end of the diff? Was that your changes, or did you forget to `git pull`.

There's a lot in here that's not just `override`

**Comment by D-K-E** [comment]
I assume the diff is due to formatting? I am using clang-format at each save, I have not noticed that it created such a huge diff. The same did not apply for the source text since I don't have a markdeep formatter. I did fetch and pull the latest change from dev-minor, and I really just added the `override` and deleted the `virtual` at the beginning of the method as I have promised in the issue.

**Comment by hollasch** [comment]
Lots of indentation differences and the like, so more than just being out of sync.

I'd suggest cloning directly from the project repo (not a fork), creating a new `overrides` branch from `dev-minor`, and pushing and PR'ing those changes.

If you still want to work from a fork, you should probably create a feature branch to work in, instead of working directly in a fork of one of our integration branches (like `dev-minor`).

**Comment by D-K-E** [comment]
All right. I'll rebase to dev-minor and do the commits in smaller chunks to an "override" branch to make it more digestable

**Pull request closed without merging**
