### PR TITLE
733: `bvh_node` breaking with negative-radius spheres

### LINKED ISSUE #733: `bvh_node` is broken with negative-radius spheres
I wanted to create some "Matryoshka hollow glass spheres", so I setup this scene:

```c++
    hittable_list world;

    const color ground_yellow(0.8, 0.8, 0);
    const color gold(0.8, 0.6, 0.2);
    const color blue(0.1, 0.2, 2);
    const color green(0.1, 0.9, 0.3);
    const double glass_refractive_index = 1.5;
    const auto ground_mat = make_shared<lambertian>(ground_yellow);
    const auto blue_mat   = make_shared<lambertian>(blue);
    const auto left_mat   = make_shared<dielectric>(glass_refractive_index);
    const auto center_mat = make_shared<lambertian>(green);
    const auto right_mat  = make_shared<metal>(gold, 1);
    const double tiny_y = 0.005;

    world.add(make_shared<sphere>(point3(-1,  tiny_y, -1),  0.5,  left_mat));
    world.add(make_shared<sphere>(point3(-1,  tiny_y, -1), -0.35, left_mat));
    world.add(make_shared<sphere>(point3(-1,  tiny_y, -1),  0.3,  left_mat));
    world.add(make_shared<sphere>(point3(-1,  tiny_y, -1), -0.2,  left_mat));
    world.add(make_shared<sphere>(point3(-1,  tiny_y, -1),  0.15, left_mat));
    world.add(make_shared<sphere>(point3(-1,  tiny_y, -1),  0.1,  blue_mat));
    world.add(make_shared<sphere>(point3( 0,  0.15 , -1),   .5,  center_mat));
    world.add(make_shared<sphere>(point3( 1,  tiny_y, -1),  0.5,  right_mat));
    world.add(make_shared<sphere>(point3( 0, -100.5, -1),   100,  ground_mat));   // The ground (Big boi)

    const bvh_node world_bvh(world, 0, 1); 

    point3 lookfrom(0, 0.25, 3.25);
    point3 lookat(0, 0, -1);
    auto vfov = 25.0;
    auto aperture = 0.0;
    color background = color(0.70, 0.80, 1.00);

    // Camera

    const vec3 vup(0,1,0);
    const auto dist_to_focus = (lookfrom - lookat).length();
    const int image_height = static_cast<int>(image_width / aspect_ratio);

    camera cam(lookfrom, lookat, vup, vfov, aspect_ratio, aperture, dist_to_focus, 0.0, 1.0);
```

When rendering on `world`, I get this, which is correct:
three_spheres_no_bvh

But when I render with `world_bvh`, this is the result:
three_spheres_bvh

I don't think that's right.

### PR DESCRIPTION
**Pull request by define-private-public**
Fix is to make sure that the AABB's is always a positive real number it
should never be negative.

Closes #733

### CODE REVIEW

**Comment by hollasch** [comment]
Are you open to making the change above to `aabb`? If so, let's see if that fixes your problem. We'll need to retarget this to `dev-major` at this point.

**Comment by define-private-public** [comment]
It's on my TODO to try out the AABB-proofing method as you suggested.

**Comment by define-private-public** [comment]
Sorry, I haven't gotten around to this yet.  I've been busy with other tasks.  You can reject this this PR if you want; I don't think I'm going to get around this soon.

**Comment by hollasch** [comment]
Ok, thanks for the clear hand-off. I'm tackling a bunch of big refactorings, so I'll just add this to my list. I'll leave this open for now to remind me, and would appreciate review feedback when I get to it.

**Comment by hollasch** [comment]
See https://github.com/RayTracing/raytracing.github.io/pull/812

**Comment by hollasch** [comment]
@define-private-public — Hopefully addressed in #812. Let me know if this doesn't work for your scenario.

**Pull request closed without merging**
