### PR TITLE
Book 3.4: Update sphere importance sampling f(x)

### PR DESCRIPTION
**Pull request by rupsis**
Addresses #1500

### CODE REVIEW

**Comment by rupsis** [comment]
@dimitry-ishenko Might want to take a peek as well.

**Comment by hollasch** [comment]
Sorry for the delay in giving feedback here. This is tightly coupled with Dimitry's issue #1536, which I believe should also be included in this change. I'm working on broadening this change to include #1536 (two paragraphs up), which covers the mapping of a point on the unit sphere to its two polar angles.

**Comment by rupsis** [comment]
> Sorry for the delay in giving feedback here. This is tightly coupled with Dimitry's issue #1536, which I believe should also be included in this change. I'm working on broadening this change to include #1536 (two paragraphs up), which covers the mapping of a point on the unit sphere to its two polar angles.

Sounds good. Want to take what I have here and roll them into your changes? 

If so, feel free to close the PR out.

**Comment by hollasch** [comment]
I'm just working in this branch.

**Review by hollasch — APPROVED** [review]

**Comment by hollasch** [comment]
I'm going to add my changes onto your own.

**Pull request merged**
