### PR TITLE
Signature mismatch: bvh_node declaration and definition

### PR DESCRIPTION
**Pull request by MattTree**
Signatures didn't match

### CODE REVIEW

**Comment by hollasch** [comment]
This is aimed at the wrong branch, and the section in question has undergone changes. The change itself is patch-level, but I don't want to have to untangle the merge conflict to slip this from `dev-patch` to `dev-major`, which is the currently active development branch.

This should target `dev-major` (our currently active development branch), and also lacks the changelog update.

Please see CONTRIBUTING.md for more information.

**Comment by MattTree** [comment]
Thank you. I now know pull request etiquette better (i.e. checking for guidelines instead of blindly sending).

**Comment by hollasch** [comment]
No worries; it's a good fix. Would you mind making the equivalent change in`dev-major`?

**Comment by MattTree** [comment]
I resolved the conflict, but if possible I'd like the diff report to reflect only the actual change instead of these large red and green regions. I'm inexperienced. Is there a way to tighten the color-coded diff report? Perhaps I could close this pull request and start over.

**Comment by MattTree** [comment]
New pull request: https://github.com/RayTracing/raytracing.github.io/pull/873

**Pull request closed without merging**
