### PR TITLE
Move method defs inside classes, remove inline

### PR DESCRIPTION
**Pull request by hollasch**
Draft changes. Still need to update books.

Thoughts?

### CODE REVIEW

**Comment by trevordblack** [comment]
I feel like we should add a 5 sentence blurb in the Overview explaining how we treat the code in book. Where we try to be some what language agnostic but use c++ as a lingua franca.

I'm also super tempted to apologize profusely for the coding style.

Also, we should probably rewrite the Overview of the first book anyway. Could do with some polish.

**Comment by trevordblack** [comment]
Do we want to explain `inline`.

We've pretty much always had a higher priorities than performance, but I feel like we had a teaching oppurtunity with `inlines` in.
Not that we used it (or that `inline` was actually doing anything)

**Comment by trevordblack** [comment]
Still need to update the books (as you mention above)

This looks thorough (and possibly complete), I'm accepting this merge.

My request is that the issue not be closed out for a while. I would like to make a once-over the code at some point (at the very very end), and this is something that I want to check.

**Review by trevordblack — APPROVED** [review]

**Comment by hollasch** [comment]
“Once-over the code”? Is this different than #778, #779?

**Comment by trevordblack** [comment]
Nope. that's exactly what I had in mind.

**Comment by hollasch** [comment]
This was just a sketch of what was possible, the actual implementation is proceeding more incrementally. In addition, re-re-realized some aspects of `inline` that are necessary in some scenarios (comments in the issue and in the inline-clean pull request).

Closing out this draft.

**Pull request closed without merging**
