### PR TITLE
Fix typo in RayTracingInOneWeekend.html

### LINKED ISSUE #856: Small typo in RayTracingInOneWeekend.html
Really small typo on the book, nothing really important, thought I'd point it out though. It appears in 6.16 Some New C++ Features.

> ...so we don't need to **prefex** these with...

### PR DESCRIPTION
**Pull request by DoodlesEpic**
Really small typo fix from prefex to prefix. fixes #856

### CODE REVIEW

**Comment by hollasch** [comment]
This PR is targeting `master`, our release branch.

**Comment by hollasch** [comment]
This needs to target our current development branch, `dev-major`.

[CONTRIBUTING.md](https://github.com/RayTracing/raytracing.github.io/blob/master/CONTRIBUTING.md)

**Comment by DoodlesEpic** [comment]
Changed it! I did read the CONTRIBUTING.md, but it wasn't clear which branch I should select so I put master as a placeholder.

**Review by hollasch — APPROVED** [review]

**Comment by hollasch** [comment]
Thank you! Merged.

**Pull request merged**
