### PR TITLE
Quad bbox should consider all four vertices

### LINKED ISSUE #1402: [Book2] bbox for quad should consider all 4 points
bounding box for quad should consider all the 4 points of quad instead of the opposite corner points, for the other 2 points could enlarge the box along that direction

### PR DESCRIPTION
**Pull request by hollasch**
Originally due to WANG Lei (https://github.com/wlbksy)

Resolves #1402

### CODE REVIEW

**Comment by hollasch** [comment]
@wlbksy — I've sent you an invite to our collaborator's group. This will allow you to make changes directly to the RTW repo without having to mess with a fork, and also to comment on reviews.

**Comment by hollasch** [comment]
NOTE: If my edits are approved, then I will be squashing everything into a single commit before merging to dev.

**Comment by wlbksy** [comment]
I'm all good. English is not my best. This CR LGTM

**Comment by wlbksy** [comment]
> NOTE: If my edits are approved, then I will be squashing everything into a single commit before merging to dev.

Why not make it automatically? See https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-squashing-for-pull-requests

**Comment by hollasch** [comment]
Squash merging is already allowed, but we do not squash everything. More complicated changes are best preserved as a sequence if logical changes. "Make the change easy, then make the easy change."

**Pull request merged**
