### PR TITLE
Fix change highlighting for listing 30, 46

### LINKED ISSUE #1313: Listing 3.30: Inconsistent change highlighting
Benny Tsang writes:
> (Book 3) Listing 30: the highlighting is inconsistent with what is modified, e.g., `attenuation` should be `alb` to be consistent with the function argument.

### PR DESCRIPTION
**Pull request by hollasch**
Resolves #1313

### CODE REVIEW

**Comment by hollasch** [comment]
@bthtsang

**Review by armansito — COMMENTED** [review]
I noticed that between listings 23 and 29 the `attenuation` parameter of `lambertian::scatter` also gets renamed to `alb` but I believe the change isn't highlighted.

This got me thinking though: why rename `attenuation` to `alb` at all? In the final state of the code albedo gets assigned to `scatter_record::attenuation` so the rename in between feels confusing to me. Ultimately "attenuation" is the right terminology.

**Comment by hollasch** [comment]
Good changes; thanks! I've incorporated your suggestions and also made a few cosmetic tweaks.

**Review by armansito — APPROVED** [review]
Thanks!

**Pull request merged**
