### PR TITLE
Prefix common header filenames with common/

### LINKED ISSUE #347: Book One, newly-typed vec3.h into "common"
Dev.

Creating a color gradient image (Listing 6)
source code looks like it wants newly-typed "vec3.h" into the common folder

### PR DESCRIPTION
**Pull request by hollasch**
Added explanatory text for the src/common/ directory, and made explicit
the location of headers in the common source directory.

Resolves #347

### CODE REVIEW

**Comment by trevordblack** [comment]
This gets a hard no from me on this one.

I hate the idea of asking the reader to put up infrastructure for books 2 and 3 when they've barely started book 1.
I understand that it's discordant that we have the repo with a common folder and the books without one. But adding the common folder is a change that I've hated from the beginning. I was okay with it because it would make our lives easier without impacting the end-user.

I'm really not happy with this change.

Sorry.

**Comment by dafhi** [comment]
Just saw the request.

I'm with Kevin on this one.  

How about

".. class, we will introduce new functionality to it throughout the book.  If you do decide to type in most of the code, in the .. *ahem* .. unlikely event that you made a boo boo, you can always check the /src/common folder for assistance.  [feels like more could be said]

**Comment by dafhi** [comment]
I'll have another look.  Been super busy

**Comment by dafhi** [comment]
I like /common for 2 reasons.

1.  top-down thinking
2.  efficiency

Snafus can occur where changes break previous Listings.  For this reason I recommend optional params in some of the headers.

The 'common' reference simply indicate to the reader an important header file for all Listings in one book

**Comment by hollasch** [comment]
See PR #387. Let readers search for each header, but set up CMake to properly pull from project + common directories without requiring path specification.

**Pull request closed without merging**
