### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by Hofer-Julian**

### CODE REVIEW

**Comment by trevordblack** [comment]
Can you check this against `dev-major`

**Comment by Hofer-Julian** [comment]
> Can you check this against `dev-major`

Done

**Comment by trevordblack** [comment]
Can you create an issue to track this

**Comment by hollasch** [comment]
Eh, let's skip the issue.

**Comment by hollasch** [comment]
Thanks @Hofer-Julian!

**Pull request merged**
