### PR TITLE
updating imag2 2.15, 2.17, 2.18 with v4 outputs

### PR DESCRIPTION
**Pull request by rupsis**
Addresses #1360 

The old V3 Perlin noise has a _slightly_ phase then V3:
```c++
// v3 noise_texture
virtual color value(double u, double v, const vec3& p) const override {
    return color(1,1,1)*0.5*(1 + sin(scale*p.z() + 10*noise.turb(p)));
  }
```

vs V4 
```c++
// v4 noise_texture
    color value(double u, double v, const point3& p) const override {
        auto s = scale * p;
        return color(1,1,1) * 0.5 * (1 + sin(s.z() + 10*noise.turb(s, 7)));
    }
```

Because of this, images 2.15, 2.17, & 2.18 don't match up with V4's output. 

Ran the steps agains V4, and updated the images

### CODE REVIEW

**Review by hollasch — APPROVED** [review]

**Comment by cccccz** [comment]
Hi I know this issue is already closed but I still want to address that the final scene seems to be using the v3 perlin texture as well.
using noise_texture in v3:
image

comparing to the output using noise_texture in v4:
image

also I think it would be nice to mention that the "sweet dream" picture(higher sample version of the final scene) will take more than 40 minutes to render on a 8-core cpu(using the tile and multithreading tech mentioned on the last chapter of Book 1), which is crazy.
 @hollasch

**Comment by rupsis** [comment]
@cccccz ooo, good catch. I'll need to update the final picture. 

I assumed "(sweet dreams)" was a little nod to how long the render would take. I.e, render overnight. 

But giving a little more indication of how long the render will take might be useful.

**Comment by hollasch** [comment]
Two things here. First, please don't fork issues by adding separate content to existing issues. This issue is now about updating three images, then an additional one, and then a recommended update to the text about rendering time.

Second, issue #779 already tracks the complete update of _all_ images in book 2. #863 tracks the complete update of all images for book 3. These issues are slotted into the release milestones because the body and code of books two and three are still undergoing major-level changes, and we don't want to have to update the images every time we modify the code.

**Comment by rupsis** [comment]
@hollasch  Sorry I should have been more clear, I was planning on updating the final image in a different issue. 

I was unaware of #779. Seems like we should hold off on image updates until all alpha-2 milestones have been completed?

**Comment by hollasch** [comment]
Yeah, I'd recommend that.

**Pull request merged**
